import { assertSupportedTimeSignature } from "./theory.js";

// Songs are static JSON, generated by scripts/generate-songs.mjs into
// public/songs/ — fetched lazily instead of bundled, so the library can
// grow without bloating the app's JS bundle.
const base = import.meta.env.BASE_URL;
const cache = new Map();

export async function loadCatalog() {
  const res = await fetch(`${base}songs/catalog.json`);
  if (!res.ok) throw new Error(`failed to load song catalog: HTTP ${res.status}`);
  return res.json();
}

export async function loadSong(id) {
  if (cache.has(id)) return cache.get(id);
  const res = await fetch(`${base}songs/${id}.json`);
  if (!res.ok) throw new Error(`failed to load song "${id}": HTTP ${res.status}`);
  const song = await res.json();
  assertSupportedTimeSignature(song);
  cache.set(id, song);
  return song;
}
