// Songs are static JSON, generated by scripts/generate-songs.mjs into
// public/songs/ (see design/TODO.md item 5) — fetched lazily instead of
// bundled, so the library can grow without bloating the app's JS bundle.
const base = import.meta.env.BASE_URL;
const cache = new Map();

export async function loadCatalog() {
  const res = await fetch(`${base}songs/catalog.json`);
  if (!res.ok) throw new Error(`failed to load song catalog: HTTP ${res.status}`);
  return res.json();
}

export async function loadSong(id) {
  if (cache.has(id)) return cache.get(id);
  const res = await fetch(`${base}songs/${id}.json`);
  if (!res.ok) throw new Error(`failed to load song "${id}": HTTP ${res.status}`);
  const song = await res.json();
  // Only 4/4 is implemented today — the notation renderer's line-breaking, the
  // transport's beat-dot indicator, and the beat_value passed to VexFlow's Voice
  // all hardcode a quarter-note beat and 4 beats/measure. Fail loudly rather than
  // silently mis-render or mis-count a song authored in another time signature.
  if (song.timeSignature !== "4/4") {
    throw new Error(`Song "${song.title}" has unsupported time signature "${song.timeSignature}" — only "4/4" is implemented`);
  }
  cache.set(id, song);
  return song;
}
